### ISSUE TITLE
.desktop file not working, setting import and export directories also not working

### ISSUE THREAD

**Issue by cyber-sushi** [flathub/org.filmulator.Filmulator#5]
Launching Filmulator from the menu doesn't do anything, while launching it from terminal with "flatpak run org.filmulator.Filmulator" works as expected. I'm assuming this is an issue with the .desktop file.
Also, trying to set an import or export directory doesn't do anything, I've tried with both xdg-desktop-portal-gnome and xdg-desktop-portal-gtk, same result. It does work if I select a single RAW file in the import directory tho.
Any idea on how to solve this?
Currently on Arch with i3

**Comment by hfiguiere** [comment]
the .desktop file comes from upstream, so it's likely where the problem is.

**Comment by hfiguiere** [comment]
From what I can see, it will need some tweaking to fix on this side.

**Comment by hfiguiere** [comment]
I fixed the desktop file. the other is a different issue and WFM. But I run standard GNOME.

**Comment by cyber-sushi** [comment]
The .desktop file works perfectly now, thanks!
On the other hand, I can't figure out what the problem might be with the import/export paths, I've also tried with xdg-desktop-portal-lxqt and it still doesn't work. Could it be that I'm missing a dependency or something?
